# Generated by Django 5.2.2 on 2025-06-07 20:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0001_initial'),
        ('recipients', '0002_recipient_address_recipient_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='The date and time when the invitation was created.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invitation',
            name='message',
            field=models.TextField(blank=True, help_text='Optional message to include with the invitation.'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='recipients',
            field=models.ManyToManyField(blank=True, help_text='Recipients who can accept this invitation.', related_name='invitations', to='recipients.recipient'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='The date and time when the invitation was last updated.'),
        ),
    ]
