# Generated by Django 5.2.2 on 2025-06-07 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0002_invitation_created_at_invitation_message_and_more'),
        ('projects', '0002_alter_project_owner_remove_project_recipients_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='project',
            field=models.ForeignKey(default=None, help_text='The project associated with this invitation.', on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='projects.project'),
            preserve_default=False,
        ),
    ]
