# Generated by Django 5.2.2 on 2025-06-07 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0004_invitation_channels_invitation_invitation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='invitation_date',
            field=models.DateTimeField(help_text='The date and time when the invitation was sent.'),
        ),
    ]
