# Generated by Django 5.2.2 on 2025-08-01 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0005_alter_invitation_invitation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='automation',
            field=models.BooleanField(default=False, help_text='Indicates whether this automation is started or not.'),
        ),
    ]
