# Generated by Django 5.2.2 on 2025-08-02 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0006_invitation_automation'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='last_reminder_sent',
            field=models.DateTimeField(blank=True, help_text='The date and time when the last reminder was sent.', null=True),
        ),
    ]
