# Generated by Django 5.2.2 on 2025-08-06 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0007_invitation_last_reminder_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='template',
            field=models.CharField(blank=True, choices=[('classic', 'Classic'), ('modern', 'Modern'), ('minimal', 'Minimal')], default='classic', max_length=50, null=True, verbose_name='Template'),
        ),
    ]
