# Generated by Django 5.2.2 on 2025-08-06 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0008_invitation_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='location',
            field=models.CharField(blank=True, help_text='Optional location for the event.', max_length=255),
        ),
    ]
