# Generated by Django 5.2.2 on 2025-08-08 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0009_invitation_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='slug',
            field=models.SlugField(blank=True, help_text='Unique identifier for the invitation.', max_length=100, null=True, unique=True),
        ),
    ]
