# Generated by Django 5.2.2 on 2025-08-08 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0010_invitation_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='is_password_protected',
            field=models.BooleanField(default=True, help_text='Indicates whether the invitation requires a password.'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='password',
            field=models.CharField(blank=True, help_text='Optional password for the invitation.', max_length=100),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='slug',
            field=models.SlugField(help_text='Unique identifier for the invitation.', max_length=100, unique=True),
        ),
    ]
