# Generated by Django 5.2.2 on 2025-08-08 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0011_invitation_is_password_protected_invitation_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='secure_invite_link',
            field=models.URLField(blank=True, help_text='Secure link for the invitation, generated automatically.'),
        ),
    ]
