# Generated by Django 5.2.2 on 2025-08-09 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0012_invitation_secure_invite_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='delivery_settings',
            field=models.JSONField(blank=True, default=dict, help_text="Custom delivery settings: {'email': True, 'sms': True, 'whatsapp': False}"),
        ),
        migrations.AddField(
            model_name='invitation',
            name='max_reminders',
            field=models.PositiveIntegerField(default=3, help_text='Max number of reminders allowed by plan.'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='max_retries',
            field=models.PositiveIntegerField(default=1, help_text='Max retries for unanswered reminders.'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='reminder_config',
            field=models.JSONField(blank=True, default=list, help_text='List of reminder times in minutes before event. Example: [1440, 60, 30]'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='reminder_message',
            field=models.TextField(blank=True, help_text='Custom message for reminders.'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='reminders_sent',
            field=models.PositiveIntegerField(default=0, help_text='How many reminders have been sent.'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='retry_count',
            field=models.PositiveIntegerField(default=0, help_text='Retry count for unanswered reminders.'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='automation',
            field=models.BooleanField(default=False, help_text='Automation enabled?'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='channels',
            field=models.CharField(choices=[('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('email', 'E-mail')], default='email', help_text='Default sending channel for invitations.', max_length=10),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='invitation_date',
            field=models.DateTimeField(help_text='Event date and time.'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='is_password_protected',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='last_reminder_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='location',
            field=models.CharField(blank=True, help_text='Optional location of the event.', max_length=255),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='message',
            field=models.TextField(blank=True, help_text='Main invitation message.'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='password',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='reminders',
            field=models.BooleanField(default=False, help_text='Enable or disable reminders.'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='secure_invite_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='template',
            field=models.CharField(choices=[('classic', 'Classic'), ('modern', 'Modern'), ('minimal', 'Minimal')], default='classic', max_length=50, verbose_name='Template'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
