# Generated by Django 5.2.2 on 2025-08-10 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0013_invitation_delivery_settings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='is_draft',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='invitation',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
