# Generated by Django 5.2.2 on 2025-08-15 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0014_invitation_is_draft_invitation_published_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='is_locked',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
