# Generated by Django 5.2.2 on 2025-08-18 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0015_invitation_is_locked'),
        ('projects', '0004_remove_project_invitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='project',
            field=models.ForeignKey(help_text='The project associated with this invitation.', on_delete=django.db.models.deletion.CASCADE, related_name='invitation', to='projects.project'),
        ),
    ]
