# Generated by Django 5.2.2 on 2025-08-18 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0016_alter_invitation_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='secure_invite_link',
            field=models.URLField(blank=True, max_length=300),
        ),
    ]
