# Generated by Django 5.2.2 on 2025-08-18 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0017_alter_invitation_secure_invite_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='being_sent',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
