# Generated by Django 5.2.2 on 2025-08-21 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0018_invitation_being_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='template_html',
            field=models.TextField(blank=True, help_text='HTML content of the template.'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='template',
            field=models.CharField(choices=[('classic', 'Classic'), ('modern', 'Modern'), ('minimal', 'Minimal'), ('editorial', 'Editorial'), ('bauhaus-black', 'Bauhaus Black'), ('blueprint', 'Blueprint'), ('premium', 'Premium')], default='classic', max_length=50, verbose_name='Template'),
        ),
    ]
