# Generated by Django 5.2.2 on 2025-08-22 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0019_invitation_template_html_alter_invitation_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='snapshot_image',
            field=models.ImageField(blank=True, null=True, upload_to='invites/snaps/%Y/%m/'),
        ),
    ]
