# Generated by Django 5.2.2 on 2025-08-22 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0020_invitation_snapshot_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='snapshot_image',
            field=models.ImageField(blank=True, null=True, upload_to='snaps/%Y/%m/'),
        ),
    ]
