# Generated by Django 5.2.2 on 2025-08-01 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_owner_remove_project_recipients_and_more'),
        ('recipients', '0003_alter_recipient_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='recipients',
            field=models.ManyToManyField(blank=True, related_name='project', to='recipients.recipient'),
        ),
    ]
