# Generated by Django 5.2.2 on 2025-08-18 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_recipients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='invitation',
        ),
    ]
