# Generated by Django 5.2.2 on 2025-06-05 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='plan_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
