# Generated by Django 5.2.2 on 2025-09-28 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_subscription_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='max_event',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='plan',
            name='max_invitee',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='plan',
            name='billing_cycle',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly'), ('lifetime', 'Lifetime')], default='monthly', max_length=20),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='billing_cycle',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly'), ('lifetime', 'Lifetime')], default='monthly', max_length=20),
        ),
    ]
