# Generated by Django 5.2.2 on 2025-08-12 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reminder_credits',
            field=models.IntegerField(default=3),
        ),
    ]
