# Generated by Django 5.2.2 on 2025-08-13 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_reminder_credits'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='recipient_quota_limit',
            field=models.PositiveIntegerField(default=200),
        ),
    ]
