# Generated by Django 5.2.2 on 2025-08-01 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipients', '0002_recipient_address_recipient_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipient',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
