# Generated by Django 5.2.2 on 2025-08-08 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipients', '0003_alter_recipient_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipient',
            options={},
        ),
        migrations.AddField(
            model_name='recipient',
            name='rsvp_status',
            field=models.CharField(choices=[('pending', 'Beklemede'), ('yes', 'Geliyor'), ('maybe', 'Emin Değil'), ('no', 'Gelmiyor')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
